replicaCount: 2

image:
  repository: 376129862558.dkr.ecr.eu-central-1.amazonaws.com/devops-realproject
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []   # EKS nodes can pull from ECR via IAM role; no docker secret needed

serviceAccount:
  create: true
  name: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

env:
  - name: APP_SECRET
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: secret-key

livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5
ingress:
  enabled: false
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
